name: "KiCad CI/CD"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**.kibot.yaml'
      - '.github/workflows/kibot.yml'
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**.kibot.yaml'
      - '.github/workflows/kibot.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  kibot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: generate PCB documentation
      uses: INTI-CMNB/KiBot@v2_k7
      with:
        config: kicad/pcb/config.kibot.yaml
        dir: 'documentation'
        schema: 'kicad/pcb/capybully.kicad_sch'
        board: 'kicad/pcb/capybully.kicad_pcb'
        verbose: 0
      continue-on-error: true

    - name: generate plate files
      uses: INTI-CMNB/KiBot@v2_k7
      with:
        config: kicad/plate/config.kibot.yaml
        dir: 'plate/topre'
        board: 'kicad/plate_topre/plate.kicad_pcb'
        verbose: 0
      continue-on-error: true

    - name: generate plate files 2
      uses: INTI-CMNB/KiBot@v2_k7
      with:
        config: kicad/plate_3u_niz/config.kibot.yaml
        dir: 'plate/3u_niz'
        board: 'kicad/plate_3u_niz/plate.kicad_pcb'
        verbose: 0
      continue-on-error: true

    - name: generate plate files 3
      uses: INTI-CMNB/KiBot@v2_k7
      with:
        config: kicad/plate_universal/config.kibot.yaml
        dir: 'plate/plate_universal'
        board: 'kicad/plate_universal/plate.kicad_pcb'
        verbose: 0
      continue-on-error: true

    - uses: EndBug/add-and-commit@v9
      with:
        add: 'plate documentation'
        message: '[kibot]'
